"""baseline_schema_aud_2026_07 (AUD-2026-07).

Revision ID: c478c5acf8f4
Revises:
Create Date: 2026-08-12 16:34:38.051590

Cutover: empty DB via ``alembic upgrade head`` from init_db; legacy DBs are
``stamp head`` after create_all+migrate_schema (do not re-run this DDL on them).
Reservation active-index data repair still lives in migrate_schema().
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c478c5acf8f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_builds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('version_name', sa.String(length=128), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=256), nullable=False),
    sa.Column('main_activity', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_builds_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_builds_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_builds_sha256'), ['sha256'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('extract_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('manifest_status', sa.String(length=32), nullable=False),
    sa.Column('manifest_version', sa.String(length=64), nullable=False),
    sa.Column('manifest_notes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)

    op.create_table('design_analysis_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_type', sa.String(length=64), nullable=False),
    sa.Column('requirement_count', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_analysis_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_analysis_history_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_analysis_history_project_id'), ['project_id'], unique=False)

    op.create_table('design_chat_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('design_chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_chat_sessions_project_id'), ['project_id'], unique=False)

    op.create_table('design_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_documents_project_id'), ['project_id'], unique=False)

    op.create_table('design_knowledge_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_knowledge_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_knowledge_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_knowledge_items_project_id'), ['project_id'], unique=False)

    op.create_table('design_logical_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('case_key', sa.String(length=128), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('preconditions_json', sa.Text(), nullable=False),
    sa.Column('logical_steps_json', sa.Text(), nullable=False),
    sa.Column('intent_steps_json', sa.Text(), nullable=False),
    sa.Column('expected_results_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('test_type', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('source_requirement_ids_json', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('automatability', sa.String(length=32), nullable=False),
    sa.Column('automation_status', sa.String(length=32), nullable=False),
    sa.Column('generation_metadata_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_logical_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_logical_cases_case_key'), ['case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_logical_cases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_logical_cases_review_status'), ['review_status'], unique=False)

    op.create_table('design_requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('req_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('req_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_requirements_req_key'), ['req_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_requirements_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('design_test_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_test_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_test_points_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_design_test_points_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('project_dir', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('app_build_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('device_udids_json', sa.Text(), nullable=False),
    sa.Column('entry_paths_json', sa.Text(), nullable=False),
    sa.Column('parallel', sa.Boolean(), nullable=False),
    sa.Column('parallel_workers', sa.Integer(), nullable=False),
    sa.Column('backend_mode', sa.String(length=32), nullable=False),
    sa.Column('web_engine', sa.String(length=32), nullable=False),
    sa.Column('wda_bundle', sa.String(length=256), nullable=False),
    sa.Column('preferred_runner_id', sa.String(length=128), nullable=True),
    sa.Column('runner_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('parent_job_id', sa.String(length=64), nullable=True),
    sa.Column('depends_on_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_app_build_id'), ['app_build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_parent_job_id'), ['parent_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('login_rate_buckets',
    sa.Column('rate_key', sa.String(length=320), nullable=False),
    sa.Column('failures_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rate_key')
    )
    op.create_table('ops_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=256), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('ops_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ops_locks_lease_until'), ['lease_until'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('runners',
    sa.Column('runner_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('project_ids_json', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('registration_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('runner_id')
    )
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runners_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runners_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runners_registration_source'), ['registration_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_runners_token_hash'), ['token_hash'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('project_dir', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('app_build_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('device_udids_json', sa.Text(), nullable=False),
    sa.Column('parallel', sa.Boolean(), nullable=False),
    sa.Column('parallel_workers', sa.Integer(), nullable=False),
    sa.Column('backend_mode', sa.String(length=32), nullable=False),
    sa.Column('web_engine', sa.String(length=32), nullable=False),
    sa.Column('wda_bundle', sa.String(length=256), nullable=False),
    sa.Column('preferred_runner_id', sa.String(length=128), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('delay_sec', sa.Integer(), nullable=False),
    sa.Column('interval_sec', sa.Integer(), nullable=False),
    sa.Column('repeat', sa.Integer(), nullable=False),
    sa.Column('stop_on_fail', sa.Boolean(), nullable=False),
    sa.Column('entry_paths_json', sa.Text(), nullable=False),
    sa.Column('runs_done', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_id', sa.String(length=64), nullable=True),
    sa.Column('last_passed', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_app_build_id'), ['app_build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_project_id'), ['project_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('oidc_sub', sa.String(length=256), nullable=False),
    sa.Column('saml_nameid', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_oidc_sub'), ['oidc_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_saml_nameid'), ['saml_nameid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('runner_id', sa.String(length=128), nullable=False),
    sa.Column('udid', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('backends_json', sa.Text(), nullable=False),
    sa.Column('health_note', sa.String(length=512), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('busy_job_id', sa.String(length=64), nullable=True),
    sa.Column('reservation_id', sa.String(length=64), nullable=True),
    sa.Column('admin_disabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.runner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_busy_job_id'), ['busy_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_runner_id'), ['runner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_udid'), ['udid'], unique=False)

    op.create_table('organization_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('project_invites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_invites_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_invites_token'), ['token'], unique=True)

    op.create_table('project_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('report_path', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_name', sa.String(length=256), nullable=False),
    sa.Column('app_build_id', sa.String(length=64), nullable=True),
    sa.Column('app_build_name', sa.String(length=256), nullable=False),
    sa.Column('app_version_name', sa.String(length=128), nullable=False),
    sa.Column('app_platform', sa.String(length=32), nullable=False),
    sa.Column('result_json_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_app_build_id'), ['app_build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_job_id'), ['job_id'], unique=True)

    op.create_table('resource_acl',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_acl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_acl_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_acl_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_acl_user_id'), ['user_id'], unique=False)

    op.create_table('resource_pools',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_resource_pool_org_name')
    )
    with op.batch_alter_table('resource_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_pools_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_pools_org_id'), ['org_id'], unique=False)

    op.create_table('device_reservations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_reservations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_reservations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_reservations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_reservations_username'), ['username'], unique=False)
        batch_op.create_index('uq_device_reservation_active', ['device_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    op.create_table('resource_pool_devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pool_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['resource_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'device_id', name='uq_resource_pool_device')
    )
    with op.batch_alter_table('resource_pool_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_pool_devices_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_pool_devices_pool_id'), ['pool_id'], unique=False)

    op.create_table('resource_pool_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pool_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['resource_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'project_id', name='uq_resource_pool_project')
    )
    with op.batch_alter_table('resource_pool_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_pool_projects_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_pool_projects_project_id'), ['project_id'], unique=False)

    op.create_table('resource_pool_runners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pool_id', sa.String(length=64), nullable=False),
    sa.Column('runner_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['resource_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.runner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'runner_id', name='uq_resource_pool_runner')
    )
    with op.batch_alter_table('resource_pool_runners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_pool_runners_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_pool_runners_runner_id'), ['runner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_pool_runners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_pool_runners_runner_id'))
        batch_op.drop_index(batch_op.f('ix_resource_pool_runners_pool_id'))

    op.drop_table('resource_pool_runners')
    with op.batch_alter_table('resource_pool_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_pool_projects_project_id'))
        batch_op.drop_index(batch_op.f('ix_resource_pool_projects_pool_id'))

    op.drop_table('resource_pool_projects')
    with op.batch_alter_table('resource_pool_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_pool_devices_pool_id'))
        batch_op.drop_index(batch_op.f('ix_resource_pool_devices_device_id'))

    op.drop_table('resource_pool_devices')
    with op.batch_alter_table('device_reservations', schema=None) as batch_op:
        batch_op.drop_index('uq_device_reservation_active', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_device_reservations_username'))
        batch_op.drop_index(batch_op.f('ix_device_reservations_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_device_reservations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_device_reservations_device_id'))

    op.drop_table('device_reservations')
    with op.batch_alter_table('resource_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_pools_org_id'))
        batch_op.drop_index(batch_op.f('ix_resource_pools_enabled'))

    op.drop_table('resource_pools')
    with op.batch_alter_table('resource_acl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_acl_user_id'))
        batch_op.drop_index(batch_op.f('ix_resource_acl_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resource_acl_resource_id'))

    op.drop_table('resource_acl')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_job_id'))
        batch_op.drop_index(batch_op.f('ix_reports_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_reports_app_build_id'))

    op.drop_table('reports')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_invites_token'))
        batch_op.drop_index(batch_op.f('ix_project_invites_project_id'))

    op.drop_table('project_invites')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_org_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_udid'))
        batch_op.drop_index(batch_op.f('ix_devices_runner_id'))
        batch_op.drop_index(batch_op.f('ix_devices_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_devices_busy_job_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_saml_nameid'))
        batch_op.drop_index(batch_op.f('ix_users_oidc_sub'))

    op.drop_table('users')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_project_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_schedules_enabled'))
        batch_op.drop_index(batch_op.f('ix_schedules_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_app_build_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runners_token_hash'))
        batch_op.drop_index(batch_op.f('ix_runners_registration_source'))
        batch_op.drop_index(batch_op.f('ix_runners_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_runners_org_id'))

    op.drop_table('runners')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    op.drop_table('organizations')
    with op.batch_alter_table('ops_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ops_locks_lease_until'))

    op.drop_table('ops_locks')
    op.drop_table('login_rate_buckets')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_runner_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_parent_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_app_build_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('design_test_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_test_points_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_design_test_points_project_id'))

    op.drop_table('design_test_points')
    with op.batch_alter_table('design_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_requirements_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_design_requirements_req_key'))
        batch_op.drop_index(batch_op.f('ix_design_requirements_project_id'))

    op.drop_table('design_requirements')
    with op.batch_alter_table('design_logical_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_logical_cases_review_status'))
        batch_op.drop_index(batch_op.f('ix_design_logical_cases_project_id'))
        batch_op.drop_index(batch_op.f('ix_design_logical_cases_case_key'))

    op.drop_table('design_logical_cases')
    with op.batch_alter_table('design_knowledge_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_knowledge_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_design_knowledge_items_category'))

    op.drop_table('design_knowledge_items')
    with op.batch_alter_table('design_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_documents_project_id'))

    op.drop_table('design_documents')
    with op.batch_alter_table('design_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_chat_sessions_project_id'))

    op.drop_table('design_chat_sessions')
    with op.batch_alter_table('design_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_chat_messages_session_id'))

    op.drop_table('design_chat_messages')
    with op.batch_alter_table('design_analysis_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_analysis_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_design_analysis_history_document_id'))

    op.drop_table('design_analysis_history')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('app_builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_builds_sha256'))
        batch_op.drop_index(batch_op.f('ix_app_builds_project_id'))
        batch_op.drop_index(batch_op.f('ix_app_builds_platform'))

    op.drop_table('app_builds')
    # ### end Alembic commands ###
