#!/usr/bin/env python3
"""从 mgmt_client_ops.json (+ OpenAPI 摘要) 生成 MgmtClient 参考 stub（ARCH-002）。

用法::
  python tools/codegen_mgmt_client_stubs.py
  python tools/codegen_mgmt_client_stubs.py --write autopilot_platform/ap/mgmt/client_ops_generated.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "contracts" / "mgmt_client_ops.json"
DEFAULT_OPENAPI = ROOT / "docs" / "openapi.v1.json"
DEFAULT_OUT = ROOT / "autopilot_platform" / "ap" / "mgmt" / "client_ops_generated.py"


def _normalize_path(path: str) -> str:
    return re.sub(r"\{[a-zA-Z_][a-zA-Z0-9_]*}", "{param}", path.strip())


def _method_name(method: str, path: str) -> str:
    raw = path.strip("/")
    slug = re.sub(r"\{param}", "by_id", raw)
    slug = slug.replace("/", "_").replace("-", "_")
    if slug.startswith("api_v1_"):
        slug = slug[7:]
    if slug == "health":
        return "get_health" if method.upper() == "GET" else f"{method.lower()}_health"
    prefix = method.lower()
    return f"{prefix}_{slug}" if slug else prefix


def _http_snippet(method: str, path: str) -> str:
    m = method.upper()
    if m == "GET":
        extra = ", params=params" if "{param}" not in path else ""
        if "{param}" in path:
            return f'r = self._client.get(f"{path}", params=params)'
        return f'r = self._client.get("{path}"{extra})'
    if m == "DELETE":
        return f'r = self._client.delete(f"{path}")' if "{param}" in path else f'r = self._client.delete("{path}")'
    body = "json=body"
    if m == "POST" and path in ("/api/v1/artifacts", "/api/v1/app-builds"):
        body = "files=files, data=data"
    if "{param}" in path:
        return f'r = self._client.{m.lower()}(f"{path}", {body})'
    return f'r = self._client.{m.lower()}("{path}", {body})'


def _load_openapi_summaries(openapi_path: Path) -> dict[tuple[str, str], str]:
    if not openapi_path.is_file():
        return {}
    spec = json.loads(openapi_path.read_text(encoding="utf-8"))
    out: dict[tuple[str, str], str] = {}
    for p, methods in (spec.get("paths") or {}).items():
        norm = _normalize_path(str(p))
        for m, meta in methods.items():
            if m.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
                continue
            if not isinstance(meta, dict):
                continue
            summary = str(meta.get("summary") or meta.get("operationId") or "").strip()
            if summary:
                out[(m.upper(), norm)] = summary
    return out


def render_stubs(manifest_path: Path, *, openapi_path: Path | None = None) -> str:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    ops: list[dict[str, str]] = list(payload.get("operations") or [])
    summaries = _load_openapi_summaries(openapi_path or DEFAULT_OPENAPI)

    lines: list[str] = [
        '"""AUTO-GENERATED by tools/codegen_mgmt_client_stubs.py — DO NOT EDIT.',
        "",
        "ARCH-002: MgmtClient HTTP 操作参考 stub。运行时请使用 mgmt.client.MgmtClient。",
        "重新生成::",
        "  1. python tools/extract_mgmt_client_ops.py --write contracts/mgmt_client_ops.json",
        "  2. python tools/codegen_mgmt_client_stubs.py --write <pkg>/mgmt/client_ops_generated.py",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "# fmt: off",
        "MGMT_CLIENT_OPERATIONS: tuple[tuple[str, str], ...] = (",
    ]
    for op in ops:
        method = op["method"].upper()
        path = op["path"]
        lines.append(f'    ("{method}", "{path}"),')
    lines.extend(
        [
            ")",
            "# fmt: on",
            "",
            "",
            "class MgmtClientOpsGenerated:",
            '    """OpenAPI/manifest 对齐的 HTTP 调用参考（非运行时代码）。"""',
            "",
            "    _client: Any",
            "",
            "    def _check(self, r: Any) -> Any:",
            '        raise NotImplementedError("reference stub")',
            "",
        ]
    )

    seen_names: set[str] = set()
    for op in ops:
        method = op["method"].upper()
        path = op["path"]
        name = _method_name(method, path)
        if name in seen_names:
            name = f"{name}_{method.lower()}"
        seen_names.add(name)
        summary = summaries.get((method, _normalize_path(path)), "")
        snippet = _http_snippet(method, path)
        doc = f"{method} {path}"
        if summary:
            doc += f" — {summary}"
        lines.extend(
            [
                f"    def {name}(self, *args: Any, **kwargs: Any) -> Any:",
                f'        """{doc}',
                "",
                "        Reference::",
                f"            {snippet}",
                "            return self._check(r)",
                '        """',
                '        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")',
                "",
            ]
        )

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="Codegen MgmtClient reference stubs")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--openapi", default=str(DEFAULT_OPENAPI))
    parser.add_argument("--write", default="", help="写入 Python 文件（默认 stdout）")
    args = parser.parse_args(argv)

    text = render_stubs(Path(args.manifest), openapi_path=Path(args.openapi))
    if args.write:
        out = Path(args.write)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        n = text.count("def ")
        print(f"[codegen_mgmt_client_stubs] wrote {out} ({n} methods)")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
