"""AUTO-GENERATED by tools/codegen_mgmt_client_stubs.py — DO NOT EDIT.

ARCH-002: MgmtClient HTTP 操作参考 stub。运行时请使用 mgmt.client.MgmtClient。
重新生成::
  1. python tools/extract_mgmt_client_ops.py --write contracts/mgmt_client_ops.json
  2. python tools/codegen_mgmt_client_stubs.py --write <pkg>/mgmt/client_ops_generated.py
"""

from __future__ import annotations

from typing import Any

# fmt: off
MGMT_CLIENT_OPERATIONS: tuple[tuple[str, str], ...] = (
    ("GET", "/api/v1/app-builds"),
    ("POST", "/api/v1/app-builds"),
    ("GET", "/api/v1/artifacts"),
    ("POST", "/api/v1/artifacts"),
    ("POST", "/api/v1/auth/ide-handoff"),
    ("POST", "/api/v1/auth/login"),
    ("POST", "/api/v1/auth/logout"),
    ("GET", "/api/v1/auth/me"),
    ("POST", "/api/v1/auth/refresh"),
    ("GET", "/api/v1/design/logical-cases"),
    ("POST", "/api/v1/design/logical-cases"),
    ("POST", "/api/v1/design/logical-cases/enqueue-job"),
    ("POST", "/api/v1/design/logical-cases/generate"),
    ("PATCH", "/api/v1/design/logical-cases/{param}"),
    ("GET", "/api/v1/design/projects/{param}/logical-cases/export"),
    ("GET", "/api/v1/devices"),
    ("POST", "/api/v1/jobs"),
    ("GET", "/api/v1/jobs/{param}"),
    ("GET", "/api/v1/ops/ai/capabilities"),
    ("POST", "/api/v1/ops/ai/codegen"),
    ("GET", "/api/v1/ops/runtime-version"),
    ("GET", "/api/v1/orgs"),
    ("GET", "/api/v1/projects"),
    ("POST", "/api/v1/projects"),
    ("POST", "/api/v1/runners/register"),
    ("POST", "/api/v1/runners/{param}/scoped-token"),
    ("GET", "/health"),
)
# fmt: on


class MgmtClientOpsGenerated:
    """OpenAPI/manifest 对齐的 HTTP 调用参考（非运行时代码）。"""

    _client: Any

    def _check(self, r: Any) -> Any:
        raise NotImplementedError("reference stub")

    def get_app_builds(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/app-builds — Api List App Builds

        Reference::
            r = self._client.get("/api/v1/app-builds", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_app_builds(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/app-builds — Api Upload App Build

        Reference::
            r = self._client.post("/api/v1/app-builds", files=files, data=data)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_artifacts(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/artifacts — Api List Artifacts

        Reference::
            r = self._client.get("/api/v1/artifacts", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_artifacts(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/artifacts — Api Upload Artifact

        Reference::
            r = self._client.post("/api/v1/artifacts", files=files, data=data)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_auth_ide_handoff(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/auth/ide-handoff — Api Create Ide Handoff

        Reference::
            r = self._client.post("/api/v1/auth/ide-handoff", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_auth_login(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/auth/login — Api Login

        Reference::
            r = self._client.post("/api/v1/auth/login", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_auth_logout(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/auth/logout — Api Logout

        Reference::
            r = self._client.post("/api/v1/auth/logout", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_auth_me(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/auth/me — Api Me

        Reference::
            r = self._client.get("/api/v1/auth/me", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_auth_refresh(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/auth/refresh — Api Refresh

        Reference::
            r = self._client.post("/api/v1/auth/refresh", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_design_logical_cases(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/design/logical-cases — Api List Logical Cases

        Reference::
            r = self._client.get("/api/v1/design/logical-cases", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_design_logical_cases(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/design/logical-cases — Api Create Logical Case

        Reference::
            r = self._client.post("/api/v1/design/logical-cases", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_design_logical_cases_enqueue_job(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/design/logical-cases/enqueue-job — Api Enqueue Approved Job

        Reference::
            r = self._client.post("/api/v1/design/logical-cases/enqueue-job", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_design_logical_cases_generate(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/design/logical-cases/generate — Api Generate Logical Cases

        Reference::
            r = self._client.post("/api/v1/design/logical-cases/generate", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def patch_design_logical_cases_by_id(self, *args: Any, **kwargs: Any) -> Any:
        """PATCH /api/v1/design/logical-cases/{param} — Api Update Logical Case

        Reference::
            r = self._client.patch(f"/api/v1/design/logical-cases/{param}", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_design_projects_by_id_logical_cases_export(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/design/projects/{param}/logical-cases/export — Api Export Approved Logical Cases

        Reference::
            r = self._client.get(f"/api/v1/design/projects/{param}/logical-cases/export", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_devices(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/devices — Api List Devices

        Reference::
            r = self._client.get("/api/v1/devices", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_jobs(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/jobs — Api Create Job

        Reference::
            r = self._client.post("/api/v1/jobs", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_jobs_by_id(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/jobs/{param} — Api Get Job

        Reference::
            r = self._client.get(f"/api/v1/jobs/{param}", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_ops_ai_capabilities(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/ops/ai/capabilities — Api Ops Ai Capabilities

        Reference::
            r = self._client.get("/api/v1/ops/ai/capabilities", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_ops_ai_codegen(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/ops/ai/codegen — Api Ops Ai Codegen

        Reference::
            r = self._client.post("/api/v1/ops/ai/codegen", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_ops_runtime_version(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/ops/runtime-version — Api Ops Runtime Version

        Reference::
            r = self._client.get("/api/v1/ops/runtime-version", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_orgs(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/orgs — Api List Orgs

        Reference::
            r = self._client.get("/api/v1/orgs", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_projects(self, *args: Any, **kwargs: Any) -> Any:
        """GET /api/v1/projects — Api List Projects

        Reference::
            r = self._client.get("/api/v1/projects", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_projects(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/projects — Api Create Project

        Reference::
            r = self._client.post("/api/v1/projects", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_runners_register(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/runners/register — Api Register

        Reference::
            r = self._client.post("/api/v1/runners/register", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def post_runners_by_id_scoped_token(self, *args: Any, **kwargs: Any) -> Any:
        """POST /api/v1/runners/{param}/scoped-token — Api Issue User Scoped Runner Token

        Reference::
            r = self._client.post(f"/api/v1/runners/{param}/scoped-token", json=body)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

    def get_health(self, *args: Any, **kwargs: Any) -> Any:
        """GET /health — Health

        Reference::
            r = self._client.get("/health", params=params)
            return self._check(r)
        """
        raise NotImplementedError("reference stub — use mgmt.client.MgmtClient")

